Migrate from Vue2 to Vue3
OSU-Sustainability-Office/sustainability_map pull request #42
Opened 2024-12-12 17:58 UTC by s-egge

This started as a dependency update, but the majority of vulnerabilities were in dependencies related to Vue CLI. Migrating from Vue CLI to Vite took the vulnerabilities from over 100 down to under 20. This PR will have a LOT of changes. 

## Vue CLI to Vite
I followed [this tutorial](https://vueschool.io/articles/vuejs-tutorials/how-to-migrate-from-vue-cli-to-vite/) for migrating to Vite, at the recommendation of the [Vue3 documentation](https://v3-migration.vuejs.org/recommendations.html). They also recommend migrating from Vuex to Pinia, which was created as a prototype for Vuex 5, but that should probably be saved for another PR. 

### Prettier / ESLint
- Babel is no longer needed
- I added the ESLint and Prettier rules from the Energy Dashboard, so there are some changes that are just in the formatting. 

## TODO
- [ ] Vue2 -> Vue3
- [ ] Merge main after [this PR](https://github.com/OSU-Sustainability-Office/sustainability_map/pull/40) is approved.

2024-12-23 23:24 UTC, s-egge commented
There are still two warnings in the console, they are from the `leaflet` library so we cannot fix them at this time. ![image](https://github.com/user-attachments/assets/c883ab4d-2b47-457c-974e-9bf94cb7b22a)

2024-12-28 21:49 UTC, brandovlee requested changes
A few minor adjustments that should be made before merging. See comments.

2024-12-28 21:49 UTC, brandovlee commented on src/store/index.js
Not urgent, but we should think about migrating to Pinia since it's recommended. This can be addressed in a different PR, but we should make an issue for this so we don't forget.

2024-12-28 21:49 UTC, brandovlee commented on vite.config.mjs
If we want to maintain consistency across all of the applications, then it should be modified to be ran on localhost:3000 instead of localhost:5173.

2024-12-28 21:49 UTC, brandovlee commented on README.md
README should be updated as it references Vue-CLI multiple times.

1) In installation steps, `npm run serve` should be changed to `npm run dev`
2) In the "Notes about the build process" section, it mentions Vue-CLI which has now been removed from the application

2024-12-28 21:49 UTC, brandovlee commented on src/components/navBar.vue
<img width="718" alt="Screenshot 2024-12-28 at 1 12 38 PM" src="https://github.com/user-attachments/assets/b25a706a-a759-48ae-abb7-e8fe999c8656" />

I noticed a slight error in the console. This was a pre-existing issue, but should be addressed. It should be resolved by setting width equal to "100%" instead of "auto."

2024-12-28 21:49 UTC, brandovlee commented on package.json
I read the PR for osmtogeojson, and it seems like they're dragging their feet with updating the xmldom since the PR has been open for over 2 years.  

Given that it's causing 2 severe vulnerabilities, I think that we should address this issue. I found this stack overflow article (https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions), and we can essentially force it to use a newer version of xmldom. 

Although the article mentions several workarounds, I believe that using specifically npm-force-resolutions will resolve the vulnerabilities.

2024-12-30 18:50 UTC, s-egge commented on src/store/index.js
[New issue made](https://github.com/OSU-Sustainability-Office/sustainability_map/issues/46)

2024-12-30 18:54 UTC, s-egge commented
ESLint 8.x is deprecated which has lead to some deprecation warnings (no vulnerabilities), but it's a dependency for some libraries that seem like they aren't being maintained any more. I made an[ issue for this](https://github.com/OSU-Sustainability-Office/sustainability_map/issues/47) as well to work on in a separate PR since this one is getting very large.

2024-12-30 22:04 UTC, brandovlee commented on src/assets/style-variables.scss
<img width="1436" alt="Screenshot 2024-12-30 at 1 54 04 PM" src="https://github.com/user-attachments/assets/129b6480-3e7b-4266-8d43-2e4346ce0e9a" />

I'm noticing that the styling isn't consistent between the master branch and this branch. When putting them side by side, the search bar and title at the top of the page has a different appearance. The sidebar also has a different appearance in the screenshot. Not 100% sure why the styling might have changed.

2024-12-30 22:09 UTC, s-egge commented on src/assets/style-variables.scss
I forgot to mention it above, but there are some differences in ElementPlus that required some different styling. It's mostly spacing things, as ElementPlus no longer has a "medium" size, it's either "default", "small", or "large". Buttons especially have some different looking spacing, and I had to change the spacing of the navbar items to match a different layout pattern they have now (all of the `el-col` items in a row need to add up to 24, previously they added up to 22 and needed adjustments to behave similarly when changing screen size). I tried to keep it as close as possible to the previous styling without going overboard on adding additional css to the built-in ElementPlus components.

2024-12-30 23:00 UTC, merged